name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # アプリケーションディレクトリに移動
            cd /home/ec2-user/express-rdb-ejs-uploader

            # 既存のプロセスを停止（必要な場合）
            pkill node || true

            # リポジトリの更新
            git pull origin develop

            # 依存関係のインストール
            npm ci

            # 環境変数ファイルの作成
            echo "${{ secrets.ENV_FILE }}" > .env

            # アプリケーションの起動（バックグラウンドで）
            nohup node app.js > app.log 2>&1 &